GREETING = "menu-greeting"
OPEN_SHOP_BUTTON = "menu-open-shop-button"
OPEN_STAFF_BUTTON = "menu-open-staff-button"
OPEN_CATALOG_BUTTON = "menu-open-catalog-button"
SHOW_SHOP_BUTTON = "menu-show-shop-button"
HIDE_SHOP_BUTTON = "menu-hide-shop-button"
