CART = "orders-cart"
CART_EMPTY = "orders-cart-empty"
CART_WITH_GONE_LINES = "orders-cart-with-gone-lines"
CART_LINE = "orders-cart-line"
CART_LINE_GONE = "orders-cart-line-gone"
CART_LINE_CARD = "orders-cart-line-card"
CART_LINE_CARD_GONE = "orders-cart-line-card-gone"
VARIANT_SUFFIX = "orders-variant-suffix"

OPEN_CART_BUTTON = "orders-open-cart-button"
MORE_BUTTON = "orders-more-button"
LESS_BUTTON = "orders-less-button"
DROP_BUTTON = "orders-drop-button"
CLEAR_BUTTON = "orders-clear-button"
SHARE_BUTTON = "orders-share-button"
CHECKOUT_BUTTON = "orders-checkout-button"
BACK_BUTTON = "orders-back-button"
CLEAR_QUESTION = "orders-clear-question"

ADDED_TO_CART = "orders-added-to-cart"
SHARE_MESSAGE = "orders-share-message"

ASK_NAME = "orders-ask-name"
ASK_PHONE = "orders-ask-phone"
ASK_ADDRESS = "orders-ask-address"
ASK_COMMENT = "orders-ask-comment"
NAME_REJECTED = "orders-name-rejected"
PHONE_REJECTED = "orders-phone-rejected"
ADDRESS_REJECTED = "orders-address-rejected"
COMMENT_REJECTED = "orders-comment-rejected"

CONFIRM = "orders-confirm"
CONFIRM_WITH_COMMENT = "orders-confirm-with-comment"
PLACE_BUTTON = "orders-place-button"
CONTACTS_BUTTON = "orders-contacts-button"
COMMENT_BUTTON = "orders-comment-button"
PLACED = "orders-placed"

ORDER_LIST = "orders-order-list"
ORDER_LIST_EMPTY = "orders-order-list-empty"
ORDER_ENTRY = "orders-order-entry"
ORDER_CARD = "orders-order-card"
ORDER_LINE = "orders-order-line"
ORDER_COMMENT = "orders-order-comment"
OPEN_ORDERS_BUTTON = "orders-open-orders-button"
CANCEL_ORDER_BUTTON = "orders-cancel-order-button"
CANCEL_QUESTION = "orders-cancel-question"
ORDER_GONE = "orders-order-gone"

STATUS_PLACED = "orders-status-placed"
STATUS_IN_WORK = "orders-status-in-work"
STATUS_PAID = "orders-status-paid"
STATUS_SHIPPED = "orders-status-shipped"
STATUS_DONE = "orders-status-done"
STATUS_CANCELLED = "orders-status-cancelled"

NOTICE_IN_WORK = "orders-notice-in-work"
NOTICE_PAID = "orders-notice-paid"
NOTICE_SHIPPED = "orders-notice-shipped"
NOTICE_DONE = "orders-notice-done"
NOTICE_CANCELLED = "orders-notice-cancelled"

SELECTION = "orders-selection"
SELECTION_LINE = "orders-selection-line"
SELECTION_LINE_GONE = "orders-selection-line-gone"
SELECTION_GONE = "orders-selection-gone"
ADOPT_BUTTON = "orders-adopt-button"
ADOPTED = "orders-adopted"
ADOPTED_PARTLY = "orders-adopted-partly"
ADOPTED_NOTHING = "orders-adopted-nothing"
OPEN_LINE_BUTTON = "orders-open-line-button"
