from telegramsales.modules.catalog.domain.exceptions import (
    BrandInUseError,
    CatalogHoldsCategoriesError,
    CatalogHoldsProductsError,
    CatalogNotEmptyError,
    CategoryHoldsProductsError,
    CategoryNotEmptyError,
    DescriptionTooLongError,
    EmptyDescriptionError,
    EmptyTitleError,
    ForeignCatalogError,
    NestingTooDeepError,
    NonPositivePriceError,
    PriceNotDiscountedError,
    ProductWithoutBrandError,
    ProductWithoutPhotoError,
    TitleTooLongError,
    TooManyPhotosError,
    TooManyVideosError,
    VariantsNotAllowedError,
)
from telegramsales.modules.catalog.presentation.bot import product_texts, texts
from telegramsales.shared.presentation.bot.errors import ErrorTexts

CATALOG_ERRORS: ErrorTexts = {
    ProductWithoutPhotoError: product_texts.NEEDS_PHOTO,
    ProductWithoutBrandError: product_texts.NEEDS_BRAND,
    TooManyPhotosError: product_texts.TOO_MANY_PHOTOS,
    TooManyVideosError: product_texts.TOO_MANY_VIDEOS,
    VariantsNotAllowedError: product_texts.VARIANTS_NOT_ALLOWED,
    NonPositivePriceError: product_texts.PRICE_NOT_POSITIVE,
    PriceNotDiscountedError: product_texts.PRICE_NOT_DISCOUNTED,
    EmptyTitleError: texts.TITLE_EMPTY,
    TitleTooLongError: texts.TITLE_TOO_LONG,
    EmptyDescriptionError: product_texts.DESCRIPTION_EMPTY,
    DescriptionTooLongError: product_texts.DESCRIPTION_TOO_LONG,
    NestingTooDeepError: texts.NESTING_TOO_DEEP,
    ForeignCatalogError: texts.FOREIGN_CATALOG,
    CatalogNotEmptyError: texts.CATALOG_NOT_EMPTY,
    CatalogHoldsProductsError: texts.CATALOG_HOLDS_PRODUCTS,
    CatalogHoldsCategoriesError: texts.CATALOG_HOLDS_CATEGORIES,
    CategoryNotEmptyError: texts.CATEGORY_NOT_EMPTY,
    CategoryHoldsProductsError: texts.CATEGORY_HOLDS_PRODUCTS,
    BrandInUseError: texts.BRAND_IN_USE,
}
