PRODUCT_LIST = "catalog-product-list"
PRODUCT_LIST_EMPTY = "catalog-product-list-empty"
PRODUCT_ITEM = "catalog-product-item"
PRODUCT_ITEM_DRAFT = "catalog-product-item-draft"
PRODUCT_ITEM_HIDDEN = "catalog-product-item-hidden"
PRODUCT_CARD = "catalog-product-card"
PRODUCT_CARD_SALE = "catalog-product-card-sale"

OPEN_PRODUCTS_BUTTON = "catalog-open-products-button"
NEW_PRODUCT_BUTTON = "catalog-new-product-button"
NAME_BUTTON = "catalog-product-name-button"
DESCRIPTION_BUTTON = "catalog-product-description-button"
PRICE_BUTTON = "catalog-product-price-button"
PUBLISH_BUTTON = "catalog-product-publish-button"
STOCK_BUTTON = "catalog-product-stock-button"
OUT_BUTTON = "catalog-product-out-button"
MEDIA_BUTTON = "catalog-product-media-button"
VARIANTS_BUTTON = "catalog-product-variants-button"

ASK_TITLE = "catalog-product-ask-title"
ASK_DESCRIPTION = "catalog-product-ask-description"
ASK_PRICE = "catalog-product-ask-price"
ASK_NEW_TITLE = "catalog-product-ask-new-title"
ASK_NEW_DESCRIPTION = "catalog-product-ask-new-description"
ASK_NEW_PRICE = "catalog-product-ask-new-price"
PRICE_REJECTED = "catalog-product-price-rejected"

MEDIA_SCREEN = "catalog-media-screen"
MEDIA_ITEM = "catalog-media-item"
MEDIA_VIDEO_ITEM = "catalog-media-video-item"
ASK_PHOTO = "catalog-ask-photo"
ASK_VIDEO = "catalog-ask-video"
ADD_PHOTO_BUTTON = "catalog-add-photo-button"
ADD_VIDEO_BUTTON = "catalog-add-video-button"
DONE_BUTTON = "catalog-done-button"

VARIANT_SCREEN = "catalog-variant-screen"
VARIANT_SCREEN_CLOSED = "catalog-variant-screen-closed"
VARIANT_ITEM = "catalog-variant-item"
VARIANT_ITEM_OUT = "catalog-variant-item-out"
ASK_AXIS = "catalog-ask-axis"
ASK_VARIANT = "catalog-ask-variant"
AXIS_BUTTON = "catalog-axis-button"
ADD_VARIANT_BUTTON = "catalog-add-variant-button"
