HUB = "catalog-hub"
HUB_CATALOGS_BUTTON = "catalog-hub-catalogs-button"
HUB_BRANDS_BUTTON = "catalog-hub-brands-button"

CATALOG_LIST = "catalog-list"
CATALOG_LIST_EMPTY = "catalog-list-empty"
CATALOG_ITEM = "catalog-item"
CATALOG_ITEM_HIDDEN = "catalog-item-hidden"
CATALOG_CARD = "catalog-card"
CATALOG_CREATE_BUTTON = "catalog-create-button"
CATALOG_ASK_TITLE = "catalog-ask-title"
CATALOG_ASK_NEW_TITLE = "catalog-ask-new-title"

CATEGORY_ITEM = "catalog-category-item"
CATEGORY_ITEM_HIDDEN = "catalog-category-item-hidden"
CATEGORY_CARD = "catalog-category-card"
CATEGORY_CREATE_BUTTON = "catalog-category-create-button"
SUBCATEGORY_CREATE_BUTTON = "catalog-subcategory-create-button"
CATEGORY_ASK_TITLE = "catalog-category-ask-title"
CATEGORY_ASK_NEW_TITLE = "catalog-category-ask-new-title"

BRAND_LIST = "catalog-brand-list"
BRAND_LIST_EMPTY = "catalog-brand-list-empty"
BRAND_ITEM = "catalog-brand-item"
BRAND_ITEM_HIDDEN = "catalog-brand-item-hidden"
BRAND_CARD = "catalog-brand-card"
BRAND_CREATE_BUTTON = "catalog-brand-create-button"
BRAND_ASK_TITLE = "catalog-brand-ask-title"
BRAND_ASK_NEW_TITLE = "catalog-brand-ask-new-title"

RENAME_BUTTON = "catalog-rename-button"
HIDE_BUTTON = "catalog-hide-button"
SHOW_BUTTON = "catalog-show-button"
DELETE_BUTTON = "catalog-delete-button"
BACK_BUTTON = "catalog-back-button"
CANCEL_BUTTON = "catalog-cancel-button"

DELETED = "catalog-deleted"

DELETE_QUESTION = "catalog-delete-question"
TITLE_REJECTED = "catalog-title-rejected"
TITLE_TAKEN = "catalog-title-taken"
