"""add notifications outbox

Revision ID: 31d383b6800d
Revises: 9e777c6650d8
Create Date: 2026-09-13 00:28:03.584899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31d383b6800d'
down_revision: Union[str, Sequence[str], None] = '9e777c6650d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'rejected')", name=op.f('ck_outbox_messages_known_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_outbox_messages_dedup_key'))
    )
    op.create_index(op.f('ix_outbox_messages_available_at'), 'outbox_messages', ['available_at'], unique=False)
    op.create_index(op.f('ix_outbox_messages_recipient_id'), 'outbox_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_recipient_id'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_available_at'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    # ### end Alembic commands ###
