"""add desk topics cards and messages

Revision ID: 9e777c6650d8
Revises: e4b29dd9e0b2
Create Date: 2026-09-12 22:23:11.080978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e777c6650d8'
down_revision: Union[str, Sequence[str], None] = 'e4b29dd9e0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desk_messages',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_message_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_desk_messages_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desk_messages')),
    sa.UniqueConstraint('customer_id', 'customer_message_id', name=op.f('uq_desk_messages_customer_id')),
    sa.UniqueConstraint('topic_message_id', name=op.f('uq_desk_messages_topic_message_id'))
    )
    op.create_index(op.f('ix_desk_messages_customer_id'), 'desk_messages', ['customer_id'], unique=False)
    op.create_table('desk_topics',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('feed', 'customer')", name=op.f('ck_desk_topics_known_kind')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_desk_topics_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_desk_topics')),
    sa.UniqueConstraint('kind', 'customer_id', name=op.f('uq_desk_topics_kind'), postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('thread_id', name=op.f('uq_desk_topics_thread_id'))
    )
    op.create_table('desk_cards',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('feed_message_id', sa.BigInteger(), nullable=True),
    sa.Column('topic_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_desk_cards_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_desk_cards'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('desk_cards')
    op.drop_table('desk_topics')
    op.drop_index(op.f('ix_desk_messages_customer_id'), table_name='desk_messages')
    op.drop_table('desk_messages')
    # ### end Alembic commands ###
