"""add notification subscriptions

Revision ID: e5d864f703dd
Revises: 31d383b6800d
Create Date: 2026-09-13 07:11:52.147173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d864f703dd'
down_revision: Union[str, Sequence[str], None] = '31d383b6800d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_subscriptions'))
    )
    op.create_index(op.f('ix_notification_subscriptions_is_on'), 'notification_subscriptions', ['is_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_subscriptions_is_on'), table_name='notification_subscriptions')
    op.drop_table('notification_subscriptions')
    # ### end Alembic commands ###
