"""allow uncategorized products

Revision ID: 84cf8bb0a9ff
Revises: 4237a301173f
Create Date: 2026-09-14 19:19:40.183068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cf8bb0a9ff'
down_revision: Union[str, Sequence[str], None] = '4237a301173f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
