"""add order manager

Revision ID: e4b29dd9e0b2
Revises: 3a5b2a258f7e
Create Date: 2026-09-12 18:05:59.101643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b29dd9e0b2'
down_revision: Union[str, Sequence[str], None] = '3a5b2a258f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('manager_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_orders_manager_id'), 'orders', ['manager_id'], unique=False)
    op.create_foreign_key(op.f('fk_orders_manager_id_staff_members'), 'orders', 'staff_members', ['manager_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_manager_id_staff_members'), 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_manager_id'), table_name='orders')
    op.drop_column('orders', 'manager_id')
    # ### end Alembic commands ###
