"""add staff customer view

Revision ID: 3a5b2a258f7e
Revises: 7109305fa033
Create Date: 2026-09-12 17:44:16.760694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5b2a258f7e'
down_revision: Union[str, Sequence[str], None] = '7109305fa033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'staff_members',
        sa.Column(
            'customer_view',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column('staff_members', 'customer_view', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_members', 'customer_view')
    # ### end Alembic commands ###
