"""add notification photo

Revision ID: 8823e8efaef9
Revises: 84cf8bb0a9ff
Create Date: 2026-09-15 19:19:09.932522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8823e8efaef9'
down_revision: Union[str, Sequence[str], None] = '84cf8bb0a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('photo_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'photo_id')
    # ### end Alembic commands ###
