"""add notification call to action

Revision ID: 4237a301173f
Revises: e5d864f703dd
Create Date: 2026-09-13 07:32:59.615982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4237a301173f'
down_revision: Union[str, Sequence[str], None] = 'e5d864f703dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_messages', sa.Column('action_key', sa.String(length=64), nullable=True))
    op.add_column('outbox_messages', sa.Column('action_data', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_messages', 'action_data')
    op.drop_column('outbox_messages', 'action_key')
    # ### end Alembic commands ###
