ASK_USER = "staff-ask-user"
ACCESS_GRANTED = "staff-access-granted"
ACCESS_REVOKED = "staff-access-revoked"
ROLE_CHANGED = "staff-role-changed"
CANCELLED = "staff-cancelled"
PICK_USER_BUTTON = "staff-pick-user-button"
CANCEL_BUTTON = "staff-cancel-button"

STAFF_LIST = "staff-list"
STAFF_LIST_EMPTY = "staff-list-empty"
MEMBER_LABEL = "staff-member-label"
MEMBER_LABEL_REVOKED = "staff-member-label-revoked"
MEMBER_CARD = "staff-member-card"
REVOKE_QUESTION = "staff-revoke-question"

ADD_MEMBER_BUTTON = "staff-add-member-button"
MAKE_OWNER_BUTTON = "staff-make-owner-button"
MAKE_MANAGER_BUTTON = "staff-make-manager-button"
REVOKE_BUTTON = "staff-revoke-button"
RESTORE_BUTTON = "staff-restore-button"
BACK_TO_LIST_BUTTON = "staff-back-to-list-button"

ROLE_OWNER = "staff-role-owner"
ROLE_MANAGER = "staff-role-manager"
